/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.notes.controller;

import org.notes.dto.AllNotes;
import org.notes.dto.Note;
import org.notes.dto.NoteRegistrationInfo;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-09-25T22:37:00.927143900+02:00[Europe/Warsaw]")
@Validated
@Tag(name = "notes", description = "the notes API")
public interface NotesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /notes
     *
     * @param noteRegistrationInfo  (optional)
     * @return response (status code 200)
     */
    @Operation(
        operationId = "createNote",
        tags = { "Create Note" },
        responses = {
            @ApiResponse(responseCode = "200", description = "response", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  Note.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/notes",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Note> createNote(
        @Parameter(name = "NoteRegistrationInfo", description = "", schema = @Schema(description = "")) @Valid @RequestBody(required = false) NoteRegistrationInfo noteRegistrationInfo
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date_update\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 777, \"title\" : \"TestNoteTitle\", \"message\" : \"test note description\", \"date_creation\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /notes/{noteId}
     *
     * @param noteId note id (required)
     * @return response (status code 200)
     */
    @Operation(
        operationId = "deleteNote",
        tags = { "Delete Note" },
        responses = {
            @ApiResponse(responseCode = "200", description = "response", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  Note.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/notes/{noteId}",
        produces = { "application/json" }
    )
    default ResponseEntity<Note> deleteNote(
        @Parameter(name = "noteId", description = "note id", required = true, schema = @Schema(description = "")) @PathVariable("noteId") Integer noteId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date_update\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 777, \"title\" : \"TestNoteTitle\", \"message\" : \"test note description\", \"date_creation\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /notes/{noteId}
     * get note by id
     *
     * @param noteId note id (required)
     * @return response (status code 200)
     */
    @Operation(
        operationId = "getById",
        tags = { "Get note by id" },
        responses = {
            @ApiResponse(responseCode = "200", description = "response", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  Note.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/notes/{noteId}",
        produces = { "application/json" }
    )
    default ResponseEntity<Note> getById(
        @Parameter(name = "noteId", description = "note id", required = true, schema = @Schema(description = "")) @PathVariable("noteId") Integer noteId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date_update\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 777, \"title\" : \"TestNoteTitle\", \"message\" : \"test note description\", \"date_creation\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /notes
     * get all note
     *
     * @return response (status code 200)
     */
    @Operation(
        operationId = "getNotes",
        tags = { "Get All Notes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "response", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  AllNotes.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/notes",
        produces = { "application/json" }
    )
    default ResponseEntity<AllNotes> getNotes(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notes\" : [ { \"date_update\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 777, \"title\" : \"TestNoteTitle\", \"message\" : \"test note description\", \"date_creation\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"date_update\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 777, \"title\" : \"TestNoteTitle\", \"message\" : \"test note description\", \"date_creation\" : \"2000-01-23T04:56:07.000+00:00\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /notes
     *
     * @param noteId note id (optional)
     * @param noteRegistrationInfo  (optional)
     * @return response (status code 200)
     */
    @Operation(
        operationId = "updateNote",
        tags = { "Update Note" },
        responses = {
            @ApiResponse(responseCode = "200", description = "response", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  Note.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/notes",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Note> updateNote(
        @Parameter(name = "noteId", description = "note id", schema = @Schema(description = "")) @Valid @RequestParam(value = "noteId", required = false) Integer noteId,
        @Parameter(name = "NoteRegistrationInfo", description = "", schema = @Schema(description = "")) @Valid @RequestBody(required = false) NoteRegistrationInfo noteRegistrationInfo
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date_update\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : 777, \"title\" : \"TestNoteTitle\", \"message\" : \"test note description\", \"date_creation\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
